name: Daily vocab update

on:
  schedule:
    - cron: '0 23 * * *'   # 매일 오전 8시 30분 KST = 23:30 UTC
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Generate words.json
        run: |
          import json, random, datetime
          pool = json.load(open("Voca/pool.json", encoding="utf-8"))
          words = random.sample(pool, 10)
          with open("Voca/words.json", "w", encoding="utf-8") as f:
              json.dump(words, f, ensure_ascii=False, indent=2)
          print("✅ words.json updated:", datetime.datetime.utcnow().isoformat())
        shell: python

      - name: Commit & push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add Voca/words.json
          git commit -m "Daily words update" || echo "No changes to commit"
          git push origin main --force
